<footer class="footer">
	<div class="part1">
		<div class="inner">
			<div class="tel"><img src="/common/img/ft_tel.png" alt=""></div>
			<ul class="ftSns">
				<li class="ftSnsXXX">
					<a href="#">
						<dl>
							<dt><img src="/common/img/ft_sns_yt.png" alt=""></dt>
							<dd>YouTube</dd>
						</dl>
					</a>
				</li>
				<li class="ftSnsXXX">
					<a href="#">
						<dl>
							<dt><img src="/common/img/ft_sns_fb.png" alt=""></dt>
							<dd>Facebook</dd>
						</dl>
					</a>
				</li>
				<li class="ftSnsXXX">
					<a href="#">
						<dl>
							<dt><img src="/common/img/ft_sns_tw.png" alt=""></dt>
							<dd>Twitter</dd>
						</dl>
					</a>
				</li>
				<li class="ftSnsXXX">
					<a href="#">
						<dl>
							<dt><img src="/common/img/ft_sns_ig.png" alt=""></dt>
							<dd>Instagram</dd>
						</dl>
					</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="part2">
		<div class="inner">
			<div class="in">
				<h2 class="logo"><a href="#"><img src="/common/img/logo.png" alt=""></a></h2>
				<ul class="layer1">
					<li>
						<h3>経営理念</h3>
						<ul class="layer2">
							<li><a href="#">採用情報</a></li>
							<li><a href="#">ブログ（利用者の様子）</a></li>
						</ul>
					</li>
					<li>
						<h3>私たちについて</h3>
						<ul class="layer2">
							<li><a href="#">CLOVERとは（会社概要）</a></li>
							<li><a href="#">トップメッセージ</a></li>
							<li><a href="#">VALUE・VISION</a></li>
						</ul>
					</li>
					<li>
						<h3>デイサービス</h3>
						<ul class="layer2">
							<li><a href="#">クローバーの介護観</a></li>
							<li><a href="#">クローバーの１日・利用料金</a></li>
							<li><a href="#">事業所の紹介</a></li>
						</ul>
					</li>
					<li>
						<h3>放課後等デイサービス</h3>
						<ul class="layer2">
							<li><a href="#">放課後等デイサービス</a></li>
						</ul>
					</li>
					<li>
						<h3>採用情報</h3>
						<ul class="layer2">
							<li><a href="#">人材育成への想い</a></li>
							<li><a href="#">社員エピソード集</a></li>
							<li><a href="#">募集要項</a></li>
						</ul>
					</li>
				</ul>
			</div>
			<p id="copyRight">Copyright © 2018 株式会社CLOVER All Rights Reserved.</p>
		</div>
	</div>
</footer>