<footer class="footer">
	<div class="part1">
		<div class="inner">
			<div class="tel"><img src="/common/img/ft_tel.png" alt=""></div>
			<ul class="ftSns">
				<li class="ftSnsXXX">
					<a href="https://www.facebook.com/%E3%82%AF%E3%83%AD%E3%83%BC%E3%83%90%E3%83%BC%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97%E6%96%B0%E5%8D%92%E6%8E%A1%E7%94%A8-480419259019130/?modal=admin_todo_tour" target="_blank">
						<dl>
							<dt><img src="/common/img/ft_sns_fb.png" alt=""></dt>
							<dd>Facebook</dd>
						</dl>
					</a>
				</li>
				<li class="ftSnsXXX">
					<a href="https://twitter.com/day_clovergroup/following?lang=ja&lang=ja&lang=ja" target="_blank">
						<dl>
							<dt><img src="/common/img/ft_sns_tw.png" alt=""></dt>
							<dd>Twitter</dd>
						</dl>
					</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="part2">
		<div class="inner">
			<div class="in">
				<h2 class="logo"><a href="#"><img src="/common/img/logo.png" alt=""></a></h2>
				<ul class="layer1">
					<li>
						<h3>3つのHappiness</h3>
						<ul class="layer2">
							<li><a href="/cast/">キャスト紹介</a></li>
							<li><a href="/philosophy/blog/index.html">ブログ</a></li>
							<li><a href="/career/">採用情報TOP</a></li>
						</ul>
					</li>
					<li>
						<h3>CLOVERとは</h3>
						<ul class="layer2">
							<li><a href="/about/">CLOVERとはTOP</a></li>
							<li><a href="/about/company/index.html">社名の由来・会社概要・沿革</a></li>
							<li><a href="/about/message/">トップメッセージ</a></li>
							<li><a href="/about/value/">VALUE・VISION・PRINCIPLE</a></li>
						</ul>
					</li>
					<li>
						<h3>デイサービス</h3>
						<ul class="layer2">
							<li><a href="/dayservice/">デイサービスTOP</a></li>
							<li><a href="/dayservice/qa/">社名の由来・会社概要・沿革</a></li>
							<li><a href="/dayservice/#office">事業所</a></li>
							<li><a href="/dayservice/care/">クローバーの介護観</a></li>
							<li><a href="/dayservice/day/">クローバーの１日・利用料金</a></li>
						</ul>
					</li>
					<li>
						<h3>放課後等デイサービス</h3>
						<ul class="layer2">
							<li><a href="/after/">放課後等デイサービスTOP</a></li>
						</ul>
					</li>
					<li>
						<h3>キャスト紹介</h3>
						<ul class="layer2">
							<li><a href="/cast/">キャスト紹介TOP</a></li>
						</ul>
					</li>
					<li>
						<h3>採用情報</h3>
						<ul class="layer2">
							<li><a href="/career/">採用情報TOP</a></li>
							<li><a href="/career/recruit/">募集要項</a></li>
						</ul>
					</li>
				</ul>
			</div>
			<p id="copyRight">Copyright © 2018 株式会社CLOVER All Rights Reserved.</p>
		</div>
	</div>
</footer>