<header class="header">
	<!--<div class="lines"><hr><hr><hr><hr><hr></div>-->

	<div class="pcHd">
		<div class="hdIn">
			<div class="colL">
				<div class="logo"><a href="/"><img src="/common/img/logo.png" alt=""></a></div>
			</div>
		<nav class="nav layer1">
			<ul>
				<li class="hdNav1"><a href="/philosophy/index.php">3つのHappiness</a></li>
				<li class="hdNav2"><a href="/about/index.php">会社情報</a></li>
				<li class="hdNav3"><a href="/dayservice/index.php">デイサービス</a></li>
				<li class="hdNav4"><a href="/after/index.php">放課後等デイサービス</a></li>
				<li class="hdNav5"><a href="http://day-clover.com/cast/">キャスト紹介</a></li>
				<li class="hdNav6"><a href="/career/index.php">採用情報</a></li>
				<li class="hdNav6"><a href="/philosophy/blog/index.php">ブログ</a></li>
			</ul>
		</nav>
			<div class="colR">
				<div class="btnWrap">
					<a class="btn withIcn icnMail" href="/form/index.php">
						<span>お問い合わせ</span>
					</a>
				</div>
			</div>
		</div>

		<!--
		<nav class="nav layer2">
			<ul>
				<li class="hdNavLower1">
					<a href="http://day-clover.com/cast/">キャスト紹介</a>
					<a href="/management/blog/">ブログ</a>
					<a href="/career/">採用情報TOP</a>
				</li>
				<li class="hdNavLower2">
					<a href="/about/">会社情報TOP</a>
					<a href="/about/clover/">社名の由来・会社概要・沿革</a>
					<a href="/about/value/">VALUE・VISION</a>
				</li>
				<li class="hdNavLower3">
					<a href="/dayservice/">デイサービスTOP</a>
					<a href="/dayservice/qa/">よくある質問</a>
					<a href="/dayservice/#office">事業所</a>
					<a href="/dayservice/care/">クローバーの介護観</a>
					<a href="/dayservice/day/">クローバーの１日・利用料金</a>
				</li>
				<li class="hdNavLower4"><a href="/after/">放課後等デイサービスTOP</a></li>
				<li class="hdNavLower5">
					<a href="http://day-clover.com/cast/">キャスト紹介TOP</a>
				</li>
				<li class="hdNavLower6">
					<a href="/career/">採用情報TOP</a>
					<a href="/career/recruit/">募集要項</a>
				</li>
                <li>
                <a href="/philosophy/blog/index.html">ブログ</a>
                </li>
			</ul>
		</nav>
		-->
	</div>

	<div class="spHd">
		<div class="hdIn">
			<div class="logo"><a href="/"><img src="/common/img/logo.png" alt=""></a></div>

			<a class="spBtnMenu" href="#"></a>

			<nav class="nav layer1">
				<ul>
					<li>
						<a class="hasLower" href="/philosophy/index.php">3つのHappiness</a>
						<nav class="nav layer2">
					       <a href="http://day-clover.com/cast/">キャスト紹介</a>
					       <a href="/philosophy/blog/index.php">ブログ</a>
					       <a href="/career/index.php">採用情報TOP</a>
						</nav>
					</li>
					<li>
						<a class="hasLower" href="/about/index.php">会社情報</a>
						<nav class="nav layer2">
							<a href="/about/index.php">会社情報TOP</a>
							<a href="/about/company/index.php">社名の由来・会社概要・沿革</a>
							<a href="/about/message/index.php">トップメッセージ</a>
							<a href="/about/value/index.php">VALUE・VISION・PRINCIPLE</a>
						</nav>
					</li>
					<li>
						<a class="hasLower" href="/dayservice/index.php">デイサービス</a>
						<nav class="nav layer2">
					       <a href="/dayservice/index.php">デイサービスTOP</a>
							<a href="/dayservice/qa/index.php">社名の由来・会社概要・沿革</a>
							<a href="/dayservice/index.php#office">事業所</a>
							<a href="/dayservice/care/index.php">クローバーの介護観</a>
							<a href="/dayservice/day/index.php">クローバーの１日・利用料金</a>
						</nav>
					</li>
					<li>
						<a class="hasLower" href="/after/index.php">放課後等デイサービス</a>
						<nav class="nav layer2">
							<a href="/after/index.php">放課後等デイサービスTOP</a>
						</nav>
					</li>
					<li>
						<a class="hasLower" href="http://day-clover.com/cast/">キャスト紹介</a>
						<nav class="nav layer2">
							<a href="http://day-clover.com/cast/">キャスト紹介TOP</a>
						</nav>
					</li>
					<li>
						<a class="hasLower" href="/career/index.php">採用情報</a>
						<nav class="nav layer2">
							<a href="/career/index.php">採用情報TOP</a>
							<a href="/career/recruit/index.php">募集要項</a>
						</nav>
					</li>
                <li>
                <a href="/philosophy/blog/index.php">ブログ</a>
                </li>
				</ul>
			</nav>
		</div>
	</div>
</header>