<header class="header">
	<!--<div class="lines"><hr><hr><hr><hr><hr></div>-->

	<div class="pcHd">
		<div class="hdIn">
			<div class="colL">
				<h1 class="logo"><a href="#"><img src="/common/img/logo.png" alt=""></a></h1>
			</div>
			<div class="colR">
				<nav class="nav layer1">
					<ul>
						<li class="hdNav1"><a href="#">プロミス</a></li>
						<li class="hdNav2"><a href="#">私たちについて</a></li>
						<li class="hdNav3"><a href="#">デイサービス</a></li>
						<li class="hdNav4"><a href="#">放課後等デイサービス</a></li>
						<li class="hdNav5"><a href="#">採用情報</a></li>
					</ul>
				</nav>
				<div class="tel"><img src="/common/img/hd_tel.png" alt=""></div>
				<div class="btnWrap">
					<a class="btn withIcn icnMail" href="/form/">
						<span>メールでの<br>お問い合わせ</span>
					</a>
				</div>
			</div>
		</div>

		<nav class="nav layer2">
			<ul>
				<li class="hdNavLower1">
					<a href="/management/">プロミス</a>
					<a href="/management/blog/">ブログ一覧</a>
				</li>
				<li class="hdNavLower2">
					<a href="/about/">私たちについてTOP</a>
					<a href="/about/clover/">CLOVERとは</a>
					<a href="/about/message/">トップメッセージ</a>
					<a href="/about/value/">VALUE・VISION・PRINCIPLE</a>
				</li>
				<li class="hdNavLower3">
					<a href="/dayservice/">デイサービスTOP</a>
					<a href="/dayservice/qa/">よくある質問</a>
					<a href="/dayservice/office/">事業所</a>
					<a href="/dayservice/care/">クローバーの介護観</a>
					<a href="/dayservice/day/">クローバーの１日・利用料金</a>
				</li>
				<li class="hdNavLower4"><a href="/after/">放課後等デイサービスTOP</a></li>
				<li class="hdNavLower5">
					<a href="/career/">採用情報TOP</a>
					<a href="/career/train/">人材育成への想い</a>
					<a href="/career/recruit/">募集要項</a>
					<a href="/career/episode/">社員エピソード集</a>
				</li>
			</ul>
		</nav>
	</div>

	<div class="spHd">
		<div class="hdIn">
			<h1 class="logo"><a href="#"><img src="/common/img/logo.png" alt=""></a></h1>

			<a class="spBtnMenu" href="#"></a>

			<nav class="nav layer1">
				<ul>
					<li>
						<a class="hasLower" href="#">プロミス</a>
						<nav class="nav layer2">
							<a href="/management/">プロミス</a>
							<a href="/management/blog/">ブログ一覧</a>
						</nav>
					</li>
					<li>
						<a class="hasLower" href="#">私たちについて</a>
						<nav class="nav layer2">
							<a href="/about/">私たちについてTOP</a>
							<a href="/about/clover/">CLOVERとは</a>
							<a href="/about/message/">トップメッセージ</a>
							<a href="/about/value/">VALUE・VISION・PRINCIPLE</a>
						</nav>
					</li>
					<li>
						<a class="hasLower" href="#">デイサービス</a>
						<nav class="nav layer2">
					       <a href="/dayservice/">デイサービスTOP</a>
							<a href="/dayservice/qa/">よくある質問</a>
							<a href="/dayservice/office/">事業所</a>
							<a href="/dayservice/care/">クローバーの介護観</a>
							<a href="/dayservice/day/">クローバーの１日・利用料金</a>
						</nav>
					</li>
					<li>
						<a class="hasLower" href="#">放課後等デイサービス</a>
						<nav class="nav layer2">
							<a href="/after/">放課後等デイサービスTOP</a>
						</nav>
					</li>
					<li>
						<a class="hasLower" href="#">採用情報</a>
						<nav class="nav layer2">
							<a href="/career/">採用情報TOP</a>
							<a href="/career/train/">人材育成への想い</a>
							<a href="/career/recruit/">募集要項</a>
							<a href="/career/episode/">社員エピソード集</a>
						</nav>
					</li>
				</ul>
			</nav>
		</div>
	</div>
</header>