<header class="header">
	<!--<div class="lines"><hr><hr><hr><hr><hr></div>-->

	<div class="pcHd">
		<div class="hdIn">
			<div class="colL">
				<h1 class="logo"><a href="/"><img src="/common/img/logo.png" alt=""></a></h1>
			</div>
			<div class="colR">
				<div class="tel"><img src="/common/img/hd_tel.png" alt=""></div>
				<div class="btnWrap">
					<a class="btn withIcn icnMail" href="/form/">
						<span>メールでの<br>お問い合わせ</span>
					</a>
				</div>
			</div>
		</div>
		<nav class="nav layer1">
			<ul>
				<li class="hdNav1"><a href="/management/">3つのHappiness</a></li>
				<li class="hdNav2"><a href="/about/">CLOVERとは</a></li>
				<li class="hdNav3"><a href="/dayservice/">デイサービス</a></li>
				<li class="hdNav4"><a href="/after/">放課後等デイサービス</a></li>
				<li class="hdNav5"><a href="/cast/">キャスト紹介</a></li>
				<li class="hdNav6"><a href="/career/">採用情報</a></li>
			</ul>
		</nav>

		<!--
		<nav class="nav layer2">
			<ul>
				<li class="hdNavLower1">
					<a href="/cast/">キャスト紹介</a>
					<a href="/management/blog/">ブログ</a>
					<a href="/career/">採用情報TOP</a>
				</li>
				<li class="hdNavLower2">
					<a href="/about/">CLOVERとはTOP</a>
					<a href="/about/clover/">社名の由来・会社概要・沿革</a>
					<a href="/about/value/">VALUE・VISION</a>
				</li>
				<li class="hdNavLower3">
					<a href="/dayservice/">デイサービスTOP</a>
					<a href="/dayservice/qa/">よくある質問</a>
					<a href="/dayservice/office/">事業所</a>
					<a href="/dayservice/care/">クローバーの介護観</a>
					<a href="/dayservice/day/">クローバーの１日・利用料金</a>
				</li>
				<li class="hdNavLower4"><a href="/after/">放課後等デイサービスTOP</a></li>
				<li class="hdNavLower5">
					<a href="/cast/">キャスト紹介TOP</a>
				</li>
				<li class="hdNavLower6">
					<a href="/career/">採用情報TOP</a>
					<a href="/career/recruit/">募集要項</a>
				</li>
			</ul>
		</nav>
		-->
	</div>

	<div class="spHd">
		<div class="hdIn">
			<h1 class="logo"><a href="#"><img src="/common/img/logo.png" alt=""></a></h1>

			<a class="spBtnMenu" href="#"></a>

			<nav class="nav layer1">
				<ul>
					<li>
						<a class="hasLower" href="#">3つのHappiness</a>
						<nav class="nav layer2">
					       <a href="/cast/">キャスト紹介</a>
					       <a href="/management/blog/">ブログ</a>
					       <a href="/career/">採用情報TOP</a>
						</nav>
					</li>
					<li>
						<a class="hasLower" href="#">CLOVERとは</a>
						<nav class="nav layer2">
							<a href="/about/">CLOVERとはTOP</a>
							<a href="/about/clover/">社名の由来・会社概要・沿革</a>
							<a href="/about/message/">トップメッセージ</a>
							<a href="/about/value/">VALUE・VISION・PRINCIPLE</a>
						</nav>
					</li>
					<li>
						<a class="hasLower" href="#">デイサービス</a>
						<nav class="nav layer2">
					       <a href="/dayservice/">デイサービスTOP</a>
							<a href="/dayservice/qa/">社名の由来・会社概要・沿革</a>
							<a href="/dayservice/office/">事業所</a>
							<a href="/dayservice/care/">クローバーの介護観</a>
							<a href="/dayservice/day/">クローバーの１日・利用料金</a>
						</nav>
					</li>
					<li>
						<a class="hasLower" href="#">放課後等デイサービス</a>
						<nav class="nav layer2">
							<a href="/after/">放課後等デイサービスTOP</a>
						</nav>
					</li>
					<li>
						<a class="hasLower" href="#">キャスト紹介</a>
						<nav class="nav layer2">
							<a href="/cast/">キャスト紹介TOP</a>
						</nav>
					</li>
					<li>
						<a class="hasLower" href="#">採用情報</a>
						<nav class="nav layer2">
							<a href="/career/">採用情報TOP</a>
							<a href="/career/recruit/">募集要項</a>
						</nav>
					</li>
				</ul>
			</nav>
		</div>
	</div>
</header>