
		<ul>
			<li class="itemSendagaya">
				<a href="/dayservice/office/sendagaya/index.php">
					<picture>
						<source media="(max-width:767px)" srcset="/common/img/top/sp_office_img_sendagaya.png">
						<img src="/common/img/top/office_img_sendagaya.png" alt="">
					</picture>
				</a>
			</li>
			<li class="itemYoyogiuehara">
				<a href="/dayservice/office/yoyogiuehara/index.php">
					<picture>
						<source media="(max-width:767px)" srcset="/common/img/top/sp_office_img_yoyogiuehara.png">
						<img src="/common/img/top/office_img_yoyogiuehara.png" alt="">
					</picture>
				</a>
			</li>
			<li class="itemHiroo">
				<a href="/dayservice/office/hiroo/index.php#">
					<picture>
						<source media="(max-width:767px)" srcset="/common/img/top/sp_office_img_hiroo.png">
						<img src="/common/img/top/office_img_hiroo.png" alt="">
					</picture>
				</a>
			</li>
			<li class="itemSangubasi">
				<a href="/dayservice/office/sangubashi/index.php#">
					<picture>
						<source media="(max-width:767px)" srcset="/common/img/top/sp_office_img_sangubasi.png">
						<img src="/common/img/top/office_img_sangubasi.png" alt="">
					</picture>
				</a>
			</li>
			<li class="itemKagurazaka">
				<a href="/dayservice/office/kagurazaka/index.php#">
					<picture>
						<source media="(max-width:767px)" srcset="/common/img/top/sp_office_img_kagurazaka.png">
						<img src="/common/img/top/office_img_kagurazaka.png" alt="">
					</picture>
				</a>
			</li>
			<li class="itemYotuya">
				<a href="/dayservice/office/shinjuku/index.php#">
					<picture>
						<source media="(max-width:767px)" srcset="/common/img/top/sp_office_img_sinjuku.png">
						<img src="/common/img/top/office_img_sinjuku.png" alt="">
					</picture>
				</a>
			</li>
			<li class="itemMotoyawata">
				<a href="/dayservice/office/motoyawata/index.php#">
					<picture>
						<source media="(max-width:767px)" srcset="/common/img/top/sp_office_img_motoyawata.png">
						<img src="/common/img/top/office_img_motoyawata.png" alt="">
					</picture>
				</a>
			</li>
			<li class="itemGakudai gakudai2">
				<a href="/dayservice/office/gakugeidaigaku/index.php#">
					<picture>
						<source media="(max-width:767px)" srcset="/common/img/top/sp_office_img_gakudai.png">
						<img src="/common/img/top/office_img_gakudai_l.png" alt="">
					</picture>
				</a>
			</li>
		</ul>